python3 = import('python').find_installation('python3')

test('test_download_progress', python3,
  args: [files('test_download_progress.py')],
  workdir: meson.project_source_root()
)

test('test_providers', python3,
  args: [files('test_providers.py')],
  workdir: meson.project_source_root()
)

test('test_schema_and_resources', python3,
  args: [files('test_schema_and_resources.py')],
  workdir: meson.project_source_root()
)

test('test_js_syntax', python3,
  args: [files('test_js_syntax.py')],
  workdir: meson.project_source_root()
)

test('test_core_state', python3,
  args: [files('test_core_state.py')],
  workdir: meson.project_source_root()
)

test('test_audio', python3,
  args: [files('test_audio.py')],
  workdir: meson.project_source_root()
)

test('test_services_downloader', python3,
  args: [files('test_services_downloader.py')],
  workdir: meson.project_source_root()
)
